Challenge 7 — Student Performance with NumPy

Create a NumPy matrix:

Students × Subjects

For example:

marks = np.array([
    [78, 85, 91, 67],
    [90, 88, 76, 95],
    [92, 91, 89, 94],
    [65, 72, 68, 70]
])

Calculate:

Average per student

Average per subject

Maximum mark

Minimum mark

Standard deviation

Students above average

Subject with highest average

Student with highest overall score

Important: Try doing it using NumPy operations rather than Python loops.

That distinction matters.

In [16]:
import numpy as np

marks = np.array([
    [78, 85, 91, 67, 32],  #student 1
    [90, 88, 76, 95, 54],  #student 2
    [92, 91, 89, 94, 53],  #student 3
    [65, 72, 68, 70, 45]   #student 4
])

print(marks)
average_marks = np.mean(marks, axis=1)
print("Average marks for each student:", average_marks)
average_marks_per_subject = np.mean(marks, axis=0)
print("Average marks for each subject:", average_marks_per_subject)
max_marks = np.max(marks, axis=1)
print("Maximum marks for each student:", max_marks)
min_marks = np.min(marks, axis=1)
print("Minimum marks for each student:", min_marks)
standard_deviation = np.std(marks, axis=1)
print("Standard deviation of marks for each student:", standard_deviation)
above_average_students = np.where(average_marks > np.mean(average_marks))[0]
print("Students with average marks above 70:", above_average_students)
subj_with_highest_avg = np.max(average_marks_per_subject)
print("Subject with the highest average marks:", subj_with_highest_avg)
highest_overall_marks = np.max(marks)
print("Highest overall marks:", highest_overall_marks)

[[78 85 91 67 32]
 [90 88 76 95 54]
 [92 91 89 94 53]
 [65 72 68 70 45]]
Average marks for each student: [70.6 80.6 83.8 64. ]
Average marks for each subject: [81.25 84.   81.   81.5  46.  ]
Maximum marks for each student: [91 95 94 72]
Minimum marks for each student: [32 54 53 45]
Standard deviation of marks for each student: [20.88635918 14.69149414 15.48418548  9.77752525]
Students with average marks above 70: [1 2]
Subject with the highest average marks: 84.0
Highest overall marks: 95
